name: SimpleTrail
version: 0.3
description: player dies when he tries to use spawnereggs
author: Theverat
website: http://www.crusoecraft.net

main: me.Theverat.simpletrail.simpletrail

softdepend: [WorldGuard, PreciousStones]